[package]
name = "dovi_tool"
version = "2.0.2"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.64.0"
license = "MIT"
build = "build.rs"

[[bin]]
name = "dovi_tool"
path = "src/main.rs"

[dependencies]
dolby_vision = { path = "dolby_vision", "features" = ["xml", "serde"] }
bitvec_helpers = { version = "3.1.2", default-features = false, features = ["bitstream-io"] }
hevc_parser = { version = "0.6.1", features = ["hevc_io"] }
madvr_parse = "1.0.1"

anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive", "wrap_help", "deprecated"] }
indicatif = "0.17.3"
regex = "1.7.1"
bitvec = "1.0.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.93", features = ["preserve_order"] }
itertools = "0.10.5"
plotters = { git = "https://github.com/plotters-rs/plotters", default-features = false, features = ["bitmap_backend", "bitmap_encoder", "all_series"] }

[dev-dependencies]
assert_cmd = "2.0.8"
assert_fs = "1.0.10"
predicates = "2.1.5"

[build-dependencies]
vergen = { version = "7.5.1", default-features = false, features = ["build", "git", "cargo"] }

[features]
default = ["system-font"]
system-font = ["plotters/ttf"]
internal-font = ["plotters/ab_glyph"]
