[package]
name = "dovi_tool"
version = "1.5.1"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.56.0"
license = "MIT"

[dependencies]
bitvec_helpers = "1.0.2"
hevc_parser = { version = "0.4.6", features = ["hevc_io"] }
dolby_vision = { path = "dolby_vision", "features" = ["xml", "serde_feature"] }
madvr_parse = { path = "madvr_parse" }
utilities_dovi = { path = "utilities_dovi" }

anyhow = "1.0.57"
clap = { version = "3.1.14", features = ["derive", "wrap_help"] }
indicatif = "0.16.2"
regex = "1.5.5"
bitvec = "1.0.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = { version = "1.0.80", features = ["preserve_order"] }
itertools = "0.10.3"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
predicates = "2.1.1"

[[bin]]
name = "dovi_tool"
path = "src/main.rs"

[workspace]
members = [
    "dolby_vision",
    "madvr_parse",
]
