[package]
name = "dovi_tool"
version = "1.5.6"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.61.0"
license = "MIT"
build = "build.rs"

[dependencies]
bitvec_helpers = "2.0.0"
hevc_parser = { version = "0.5.0", features = ["hevc_io"] }
dolby_vision = { path = "dolby_vision", "features" = ["xml", "serde_feature"] }
madvr_parse = "1.0.1"

anyhow = "1.0.65"
clap = { version = "3.2.22", features = ["derive", "wrap_help", "deprecated"] }
indicatif = "0.17.1"
regex = "1.6.0"
bitvec = "1.0.1"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = { version = "1.0.85", features = ["preserve_order"] }
itertools = "0.10.4"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
predicates = "2.1.1"

[build-dependencies]
vergen = { version = "7.4.2", default-features = false, features = ["build", "git", "cargo"] }

[[bin]]
name = "dovi_tool"
path = "src/main.rs"

[workspace]
members = [
    "dolby_vision",
]
