[package]
name = "dolby_vision"
version = "1.6.5"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.56.0"
license = "MIT"
description = "Dolby Vision metadata parsing and writing"
repository = "https://github.com/quietvoid/dovi_tool/tree/main/dolby_vision"

[dependencies]
bitvec_helpers = "1.0.2"
anyhow = "1.0.57"
bitvec = "1.0.0"
crc = "3.0.0"
serde = { version = "1.0.137", features = ["derive"], "optional" = true }
serde_json = { version = "1.0.81", features = ["preserve_order"], "optional" = true }
roxmltree = { version = "0.14.1", optional = true }

libc = { version = "0.2.126", optional = true }

[features]
xml = ["roxmltree"]
serde_feature = ["serde", "serde_json"]
capi = ["libc"]

[package.metadata.docs.rs]
all-features = true

[package.metadata.capi.header]
subdirectory = "libdovi"
name = "rpu_parser"

[package.metadata.capi.pkg_config]
strip_include_path_components = 1
subdirectory = false
name = "dovi"
filename = "dovi"

[package.metadata.capi.library]
rustflags = "-Cpanic=abort"
name = "dovi"

[lib]
doctest = false
